### ISSUE TITLE
Installation failure in Mac OS 

### ISSUE THREAD

**Issue by gbrigens** [Giulio2002/beth#2]
@Giulio2002  am running into `cp: /bin/bsol: Read-only file system` issues when am installing the script on MacOS BigSur. This might be due to mac os permissions I guess which doed not allow writing to bin folder even with `sudo`.
I will appreciate your help.

**Comment by gbrigens** [comment]
I tried running it directly works fine but no benchmarking are displayed. If I passs wrong arguments am able to receive help, when I correct with corect detail it runs and no stats shown. What I did...;
1. Clone the repo.
2. `cd  bsol`
3. `go build`
4. `./bsol --sol N.sol --execution-time`

Northing is displayed on the terminal. If I pass wrong argument am able to see some errors. Funny thing no result when I pass correct arguments.

**Comment by Giulio2002** [comment]
Try using sudo. like sudo sh install.sh

**Comment by gbrigens** [comment]
> Try using sudo. like sudo sh install.sh

I tried sudo as well same thing on MacOS. On Linux is unable to download from repo inlcuded in the import.

**Comment by saptarsi96** [comment]
yeah its not working on MacOS. Any help will be appreciated.

**Comment by Giulio2002** [comment]
As of now, this repository is using an outdated version of Erigon ake turbo-geth and was an old project of mine, which is now archived

**Comment by Giulio2002** [comment]
If you want to fix it go ahead but support for the project is discontinued
